[fetch_caida_spoofer_api_data.py]
logging_tag = caida_spoofer_fetcher
caida_spoofer_api_url = https://api.spoofer.caida.org/sessions
caida_items_per_page = 10000
caida_fetch_last_days = 7
data_dir = data/spoofer

[script_config.py]
logging_tag = caida_spoofer_script_config
