[tasks.py]
logging_tag = apnic_dnssec_tasks
data_dir = /data

[update_dnssec_table.py]
logging_tag = update_dnssec_table.py
data_dir = /data

[apnic_dnssec_fetcher.py]
logging_tag = apnic_dnssec_fetcher.py
data_dir = /data
apnic_dnssec_base_url = https://stats.labs.apnic.net/dnssec
apnic_dnssec_json_url = https://stats.labs.apnic.net/cgi-bin/json-table.pl
apnic_dnssec_country_workers = 8
apnic_dnssec_stats_workers = 24
apnic_dnssec_insert_batch_size = 500

[apnic_dnssec_country_fetcher.py]
logging_tag = apnic_dnssec_country_fetcher.py
data_dir = /data
apnic_dnssec_json_url = https://stats.labs.apnic.net/cgi-bin/json-table.pl
apnic_dnssec_country_workers = 16
apnic_dnssec_insert_batch_size = 100

[script_config.py]
logging_tag = apnic_dnssec_script_config.py
