[tasks.py]
logging_tag = manycast_tasks
data_dir = /data

[load_anycast_table.py]
logging_tag = load_anycast_table.py
data_dir = /data

[fetcher.py]
logging_tag = manycast_fetcher.py
manycast_ipv4_url = https://manycast.net/api/v1/export/IPv4-latest.parquet
manycast_ipv6_url = https://manycast.net/api/v1/export/IPv6-latest.parquet

[script_config.py]
logging_tag = manycast_script_config.py
