"""Create or update the PostgreSQL schema for dns_resilience_observatory."""

from __future__ import annotations

import os

import psycopg
from dotenv import dotenv_values, load_dotenv
from loguru import logger


def build_dsn() -> str:
    load_dotenv()
    env = {**dotenv_values(), **dict(os.environ)}

    db_url = env.get("DATABASE_URL")
    if db_url:
        return db_url

    host = env.get("DATABASE_HOST", "localhost")
    port = env.get("DATABASE_PORT", "5432")
    user = env.get("DATABASE_USER", "postgres")
    password = env.get("DATABASE_PASSWORD", "")
    name = env.get("DATABASE_NAME", "dns_resilience_observatory")

    if password:
        return f"postgresql://{user}:{password}@{host}:{port}/{name}"
    return f"postgresql://{user}@{host}:{port}/{name}"


STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS resolver (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ipv4 TEXT,
        ipv6 TEXT,
        asn INTEGER,
        bgp_prefix TEXT,
        org TEXT,
        org_short TEXT,
        country TEXT,
        city TEXT,
        latitude DOUBLE PRECISION,
        longitude DOUBLE PRECISION,
        is_public BOOLEAN NOT NULL,
        last_observation_ts TIMESTAMPTZ NOT NULL,
        source TEXT NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS forwarder (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ipv4 TEXT,
        ipv6 TEXT,
        resolver_id BIGINT NOT NULL REFERENCES resolver(id),
        asn INTEGER,
        bgp_prefix TEXT,
        org TEXT,
        org_short TEXT,
        country TEXT,
        city TEXT,
        latitude DOUBLE PRECISION,
        longitude DOUBLE PRECISION,
        last_observation_ts TIMESTAMPTZ NOT NULL,
        source TEXT NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS anycast (
        resolver_id BIGINT NOT NULL REFERENCES resolver(id),
        instance_id INTEGER NOT NULL,
        ipv4 TEXT,
        ipv6 TEXT,
        netmask TEXT,
        asn INTEGER,
        bgp_prefix TEXT,
        org TEXT,
        org_short TEXT,
        country TEXT,
        city TEXT,
        latitude DOUBLE PRECISION,
        longitude DOUBLE PRECISION,
        last_observation_ts TIMESTAMPTZ NOT NULL,
        source TEXT NOT NULL,
        PRIMARY KEY (resolver_id, instance_id)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS spoofer (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        last_observed_ts TIMESTAMPTZ,
        ipv4 TEXT,
        ipv6 TEXT,
        asn INTEGER,
        privatespoof BOOLEAN,
        routedspoof BOOLEAN,
        nat BOOLEAN,
        privatespoof6 BOOLEAN,
        routedspoof6 BOOLEAN,
        nat6 BOOLEAN,
        source TEXT
    );
    """,
    """
    ALTER TABLE resolver
        ADD COLUMN IF NOT EXISTS ipv4 TEXT,
        ADD COLUMN IF NOT EXISTS ipv6 TEXT,
        ADD COLUMN IF NOT EXISTS asn INTEGER,
        ADD COLUMN IF NOT EXISTS bgp_prefix TEXT,
        ADD COLUMN IF NOT EXISTS org TEXT,
        ADD COLUMN IF NOT EXISTS org_short TEXT,
        ADD COLUMN IF NOT EXISTS country TEXT,
        ADD COLUMN IF NOT EXISTS city TEXT,
        ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS is_public BOOLEAN,
        ADD COLUMN IF NOT EXISTS last_observation_ts TIMESTAMPTZ,
        ADD COLUMN IF NOT EXISTS source TEXT;
    """,
    """
    ALTER TABLE forwarder
        ADD COLUMN IF NOT EXISTS ipv4 TEXT,
        ADD COLUMN IF NOT EXISTS ipv6 TEXT,
        ADD COLUMN IF NOT EXISTS resolver_id BIGINT,
        ADD COLUMN IF NOT EXISTS asn INTEGER,
        ADD COLUMN IF NOT EXISTS bgp_prefix TEXT,
        ADD COLUMN IF NOT EXISTS org TEXT,
        ADD COLUMN IF NOT EXISTS org_short TEXT,
        ADD COLUMN IF NOT EXISTS country TEXT,
        ADD COLUMN IF NOT EXISTS city TEXT,
        ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS last_observation_ts TIMESTAMPTZ,
        ADD COLUMN IF NOT EXISTS source TEXT;
    """,
    """
    ALTER TABLE anycast
        ADD COLUMN IF NOT EXISTS ipv4 TEXT,
        ADD COLUMN IF NOT EXISTS ipv6 TEXT,
        ADD COLUMN IF NOT EXISTS netmask TEXT,
        ADD COLUMN IF NOT EXISTS asn INTEGER,
        ADD COLUMN IF NOT EXISTS bgp_prefix TEXT,
        ADD COLUMN IF NOT EXISTS org TEXT,
        ADD COLUMN IF NOT EXISTS org_short TEXT,
        ADD COLUMN IF NOT EXISTS country TEXT,
        ADD COLUMN IF NOT EXISTS city TEXT,
        ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS last_observation_ts TIMESTAMPTZ,
        ADD COLUMN IF NOT EXISTS source TEXT;
    """,
    """
    ALTER TABLE spoofer
        ADD COLUMN IF NOT EXISTS last_observed_ts TIMESTAMPTZ,
        ADD COLUMN IF NOT EXISTS ipv4 TEXT,
        ADD COLUMN IF NOT EXISTS ipv6 TEXT,
        ADD COLUMN IF NOT EXISTS asn INTEGER,
        ADD COLUMN IF NOT EXISTS privatespoof BOOLEAN,
        ADD COLUMN IF NOT EXISTS routedspoof BOOLEAN,
        ADD COLUMN IF NOT EXISTS nat BOOLEAN,
        ADD COLUMN IF NOT EXISTS privatespoof6 BOOLEAN,
        ADD COLUMN IF NOT EXISTS routedspoof6 BOOLEAN,
        ADD COLUMN IF NOT EXISTS nat6 BOOLEAN,
        ADD COLUMN IF NOT EXISTS source TEXT;
    """,
    """
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'resolver_ipv4_ipv6_check'
        ) THEN
            ALTER TABLE resolver
                ADD CONSTRAINT resolver_ipv4_ipv6_check
                CHECK (ipv4 IS NOT NULL OR ipv6 IS NOT NULL);
        END IF;
    END $$;
    """,
    """
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'forwarder_ipv4_ipv6_check'
        ) THEN
            ALTER TABLE forwarder
                ADD CONSTRAINT forwarder_ipv4_ipv6_check
                CHECK (ipv4 IS NOT NULL OR ipv6 IS NOT NULL);
        END IF;
    END $$;
    """,
    """
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_proc
            WHERE proname = 'set_anycast_instance_id'
        ) THEN
            CREATE OR REPLACE FUNCTION set_anycast_instance_id()
            RETURNS TRIGGER AS $func$
            BEGIN
                IF NEW.instance_id IS NULL THEN
                    SELECT COALESCE(MAX(instance_id), 0) + 1
                    INTO NEW.instance_id
                    FROM anycast
                    WHERE resolver_id = NEW.resolver_id;
                END IF;
                RETURN NEW;
            END;
            $func$ LANGUAGE plpgsql;
        END IF;
    END $$;
    """,
    """
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_trigger
            WHERE tgname = 'anycast_instance_id_trigger'
        ) THEN
            CREATE TRIGGER anycast_instance_id_trigger
            BEFORE INSERT ON anycast
            FOR EACH ROW
            EXECUTE FUNCTION set_anycast_instance_id();
        END IF;
    END $$;
    """,
]


def apply_schema() -> None:
    dsn = build_dsn()
    logger.info("Applying schema to dns_resilience_observatory")
    with psycopg.connect(dsn, autocommit=True) as connection:
        with connection.cursor() as cursor:
            for statement in STATEMENTS:
                cursor.execute(statement)
    logger.info("Schema update complete")


def main() -> None:
    apply_schema()


if __name__ == "__main__":
    main()
