"""Create or update the PostgreSQL schema for dns_resilience_observatory."""

from __future__ import annotations

import os

import psycopg
from dotenv import dotenv_values, load_dotenv
from loguru import logger


def build_dsn() -> str:
    load_dotenv()
    env = {**dotenv_values(), **dict(os.environ)}

    db_url = env.get("DATABASE_URL")
    if db_url:
        return db_url

    host = env.get("DATABASE_HOST", "localhost")
    port = env.get("DATABASE_PORT", "5432")
    user = env.get("DATABASE_USER", "postgres")
    password = env.get("DATABASE_PASSWORD", "")
    name = env.get("DATABASE_NAME", "dns_resilience_observatory")

    if password:
        return f"postgresql://{user}:{password}@{host}:{port}/{name}"
    return f"postgresql://{user}@{host}:{port}/{name}"


STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS data_source (
        source TEXT PRIMARY KEY,
        date_added DATE NOT NULL DEFAULT CURRENT_DATE,
        url TEXT,
        api_endpoint TEXT,
        documentation_endpoint TEXT,
        description TEXT,
        apikey_required BOOLEAN NOT NULL DEFAULT FALSE,
        last_retrieved_ts TIMESTAMPTZ,
        added_ts TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS country_location (
        country TEXT PRIMARY KEY,
        latitude DOUBLE PRECISION,
        longitude DOUBLE PRECISION
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS resolver_id (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        last_update_ts TIMESTAMPTZ NOT NULL,
        total_measurements INTEGER NOT NULL,
        seen_measurements INTEGER NOT NULL,
        verified BOOLEAN NOT NULL DEFAULT FALSE
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS resolver (
        ip INET PRIMARY KEY,
        resolver_id BIGINT NOT NULL REFERENCES resolver_id(id) ON DELETE CASCADE,
        is_public BOOLEAN NOT NULL,
        last_update_ts TIMESTAMPTZ NOT NULL,
        source TEXT NOT NULL REFERENCES data_source(source)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS resolver_service (
        resolver_id BIGINT NOT NULL REFERENCES resolver_id(id) ON DELETE CASCADE,
        protocol TEXT NOT NULL,
        port INTEGER NOT NULL CHECK (port > 0 AND port <= 65535),
        supported BOOLEAN NOT NULL DEFAULT TRUE,
        last_update_ts TIMESTAMPTZ NOT NULL,
        PRIMARY KEY (resolver_id, protocol, port)
    );
    """,
    """
    ALTER TABLE resolver_service
        ADD COLUMN IF NOT EXISTS supported BOOLEAN NOT NULL DEFAULT TRUE;
    """,
    """
    CREATE TABLE IF NOT EXISTS resolver_dohpath (
        resolver_id BIGINT PRIMARY KEY REFERENCES resolver_id(id) ON DELETE CASCADE,
        dohpath TEXT NOT NULL,
        last_update_ts TIMESTAMPTZ NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS resolver_asn (
        resolver_id BIGINT PRIMARY KEY REFERENCES resolver_id(id) ON DELETE CASCADE,
        asn INTEGER NOT NULL,
        last_update_ts TIMESTAMPTZ NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS resolver_prefix (
        resolver_id BIGINT PRIMARY KEY REFERENCES resolver_id(id) ON DELETE CASCADE,
        prefix CIDR NOT NULL,
        last_update_ts TIMESTAMPTZ NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS resolver_org (
        resolver_id BIGINT PRIMARY KEY REFERENCES resolver_id(id) ON DELETE CASCADE,
        org TEXT NOT NULL,
        last_update_ts TIMESTAMPTZ NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS resolver_location (
        resolver_id BIGINT PRIMARY KEY REFERENCES resolver_id(id) ON DELETE CASCADE,
        country TEXT NOT NULL REFERENCES country_location(country),
        city TEXT,
        last_update_ts TIMESTAMPTZ NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS resolver_domain (
        resolver_id BIGINT PRIMARY KEY REFERENCES resolver_id(id) ON DELETE CASCADE,
        domain TEXT NOT NULL,
        last_update_ts TIMESTAMPTZ NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS resolver_verification (
        resolver_id BIGINT NOT NULL REFERENCES resolver_id(id) ON DELETE CASCADE,
        verifying_source TEXT NOT NULL,
        PRIMARY KEY (resolver_id, verifying_source)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS qmin_resolver (
        resolver_id BIGINT PRIMARY KEY REFERENCES resolver_id(id) ON DELETE CASCADE,
        qmin TEXT,
        max_minimise_count INTEGER,
        minimize_one_lab INTEGER,
        last_update_ts TIMESTAMPTZ NOT NULL,
        first_qmin_observation TIMESTAMPTZ,
        last_qmin_observation TIMESTAMPTZ,
        source TEXT NOT NULL REFERENCES data_source(source)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS forwarder_id (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        last_update_ts TIMESTAMPTZ NOT NULL,
        total_measurements INTEGER NOT NULL,
        seen_measurements INTEGER NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS forwarder (
        ip INET PRIMARY KEY,
        forwarder_id BIGINT NOT NULL REFERENCES forwarder_id(id) ON DELETE CASCADE,
        is_public BOOLEAN NOT NULL,
        last_update_ts TIMESTAMPTZ NOT NULL,
        type TEXT NOT NULL,
        transparent_count BIGINT NOT NULL DEFAULT 0,
        recursive_count BIGINT NOT NULL DEFAULT 0,
        last_observed_as_recursive TIMESTAMPTZ,
        last_observed_as_transparent TIMESTAMPTZ,
        source TEXT NOT NULL REFERENCES data_source(source)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS forwarder_protocol (
        forwarder_id BIGINT NOT NULL REFERENCES forwarder_id(id) ON DELETE CASCADE,
        protocol TEXT NOT NULL,
        supported BOOLEAN NOT NULL DEFAULT TRUE,
        last_update_ts TIMESTAMPTZ NOT NULL,
        PRIMARY KEY (forwarder_id, protocol)
    );
    """,
    """
    ALTER TABLE forwarder_protocol
        ADD COLUMN IF NOT EXISTS supported BOOLEAN NOT NULL DEFAULT TRUE;
    """,
    """
    CREATE TABLE IF NOT EXISTS forwarder_endpoint (
        forwarder_id BIGINT PRIMARY KEY REFERENCES forwarder_id(id) ON DELETE CASCADE,
        endpoint TEXT NOT NULL,
        last_update_ts TIMESTAMPTZ NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS forwarder_asn (
        forwarder_id BIGINT PRIMARY KEY REFERENCES forwarder_id(id) ON DELETE CASCADE,
        asn INTEGER NOT NULL,
        last_update_ts TIMESTAMPTZ NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS forwarder_prefix (
        forwarder_id BIGINT PRIMARY KEY REFERENCES forwarder_id(id) ON DELETE CASCADE,
        prefix CIDR NOT NULL,
        last_update_ts TIMESTAMPTZ NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS forwarder_org (
        forwarder_id BIGINT PRIMARY KEY REFERENCES forwarder_id(id) ON DELETE CASCADE,
        org TEXT NOT NULL,
        last_update_ts TIMESTAMPTZ NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS forwarder_location (
        forwarder_id BIGINT PRIMARY KEY REFERENCES forwarder_id(id) ON DELETE CASCADE,
        country TEXT NOT NULL REFERENCES country_location(country),
        city TEXT,
        last_update_ts TIMESTAMPTZ NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS forwarder_domain (
        forwarder_id BIGINT PRIMARY KEY REFERENCES forwarder_id(id) ON DELETE CASCADE,
        domain TEXT NOT NULL,
        last_update_ts TIMESTAMPTZ NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS forwarder_resolver_upstream (
        forwarder_id BIGINT NOT NULL REFERENCES forwarder_id(id) ON DELETE CASCADE,
        upstream_resolver_id BIGINT NOT NULL REFERENCES resolver_id(id) ON DELETE CASCADE,
        last_update_ts TIMESTAMPTZ NOT NULL,
        PRIMARY KEY (forwarder_id, upstream_resolver_id)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS forwarder_forwarder_upstream (
        forwarder_id BIGINT NOT NULL REFERENCES forwarder_id(id) ON DELETE CASCADE,
        upstream_forwarder_id BIGINT NOT NULL REFERENCES forwarder_id(id) ON DELETE CASCADE,
        last_update_ts TIMESTAMPTZ NOT NULL,
        PRIMARY KEY (forwarder_id, upstream_forwarder_id)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS anycast (
        prefix CIDR PRIMARY KEY,
        backing_prefix CIDR,
        partial BOOLEAN NOT NULL DEFAULT FALSE,
        last_update_ts TIMESTAMPTZ NOT NULL,
        source TEXT NOT NULL REFERENCES data_source(source)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS anycast_asn (
        prefix CIDR NOT NULL REFERENCES anycast(prefix) ON DELETE CASCADE,
        asn BIGINT NOT NULL,
        last_update_ts TIMESTAMPTZ NOT NULL,
        source TEXT NOT NULL REFERENCES data_source(source),
        PRIMARY KEY (prefix, asn)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS anycast_country_backend (
        prefix CIDR NOT NULL REFERENCES anycast(prefix) ON DELETE CASCADE,
        country TEXT NOT NULL REFERENCES country_location(country),
        country_count INTEGER NOT NULL,
        last_update_ts TIMESTAMPTZ NOT NULL,
        source TEXT NOT NULL REFERENCES data_source(source),
        PRIMARY KEY (prefix, country)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS anycast_asn_backend (
        prefix CIDR NOT NULL REFERENCES anycast(prefix) ON DELETE CASCADE,
        asn BIGINT NOT NULL,
        asn_count INTEGER NOT NULL,
        last_update_ts TIMESTAMPTZ NOT NULL,
        source TEXT NOT NULL REFERENCES data_source(source),
        PRIMARY KEY (prefix, asn)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS spoofing (
        prefix CIDR PRIMARY KEY,
        nat BOOLEAN,
        privatespoof TEXT,
        routedspoof TEXT,
        last_update_ts TIMESTAMPTZ NOT NULL,
        source TEXT NOT NULL REFERENCES data_source(source)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS spoofing_asn (
        prefix CIDR PRIMARY KEY REFERENCES spoofing(prefix) ON DELETE CASCADE,
        asn BIGINT NOT NULL
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS spoofing_country (
        prefix CIDR PRIMARY KEY REFERENCES spoofing(prefix) ON DELETE CASCADE,
        country TEXT NOT NULL REFERENCES country_location(country)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS dnssec_resolver (
        ip INET PRIMARY KEY REFERENCES resolver(ip) ON DELETE CASCADE,
        validates BOOLEAN,
        total_measurements INTEGER NOT NULL,
        seen_measurements INTEGER NOT NULL,
        validation_count INTEGER NOT NULL,
        last_update_ts TIMESTAMPTZ NOT NULL,
        source TEXT NOT NULL REFERENCES data_source(source)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS dnssec_measurement_run (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        run_key TEXT NOT NULL UNIQUE,
        started_at TIMESTAMPTZ NOT NULL,
        finished_at TIMESTAMPTZ,
        status TEXT NOT NULL CHECK (status IN ('running', 'complete', 'failed')),
        query_name TEXT NOT NULL,
        output_file TEXT NOT NULL,
        source TEXT NOT NULL REFERENCES data_source(source),
        target_count BIGINT NOT NULL DEFAULT 0,
        validating_count BIGINT NOT NULL DEFAULT 0,
        non_validating_count BIGINT NOT NULL DEFAULT 0,
        unknown_count BIGINT NOT NULL DEFAULT 0,
        error TEXT
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS dnssec_resolver_observation (
        run_id BIGINT NOT NULL REFERENCES dnssec_measurement_run(id) ON DELETE CASCADE,
        ip INET NOT NULL REFERENCES resolver(ip) ON DELETE CASCADE,
        observed_at TIMESTAMPTZ NOT NULL,
        validates BOOLEAN,
        outcome TEXT NOT NULL CHECK (outcome IN ('validates', 'does_not_validate', 'unknown')),
        zdns_status TEXT NOT NULL,
        duration_seconds DOUBLE PRECISION CHECK (duration_seconds IS NULL OR duration_seconds >= 0),
        PRIMARY KEY (run_id, ip),
        CHECK (
            (outcome = 'validates' AND validates IS TRUE)
            OR (outcome = 'does_not_validate' AND validates IS FALSE)
            OR (outcome = 'unknown' AND validates IS NULL)
        )
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS dnssec_resolver_dobit (
        ip INET PRIMARY KEY REFERENCES resolver(ip) ON DELETE CASCADE,
        dobit_set BOOLEAN,
        total_measurements INTEGER NOT NULL,
        seen_measurements INTEGER NOT NULL,
        dobit_count INTEGER NOT NULL,
        last_update_ts TIMESTAMPTZ NOT NULL,
        source TEXT NOT NULL REFERENCES data_source(source)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS dnssec_asn (
        asn BIGINT PRIMARY KEY,
        validating BIGINT NOT NULL,
        validating_pc FLOAT NOT NULL,
        partial_validating BIGINT NOT NULL,
        partial_validating_pc FLOAT NOT NULL,
        last_update_ts TIMESTAMPTZ NOT NULL,
        source TEXT NOT NULL REFERENCES data_source(source)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS dnssec_country (
        country TEXT PRIMARY KEY REFERENCES country_location(country),
        validating BIGINT NOT NULL,
        validating_pc FLOAT NOT NULL,
        partial_validating BIGINT NOT NULL,
        partial_validating_pc FLOAT NOT NULL,
        last_update_ts TIMESTAMPTZ NOT NULL,
        source TEXT NOT NULL REFERENCES data_source(source)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS manrs_asn (
        asn BIGINT PRIMARY KEY CHECK (asn > 0 AND asn <= 4294967295),
        anti_spoofing_score DOUBLE PRECISION CHECK (anti_spoofing_score IS NULL OR anti_spoofing_score BETWEEN 0 AND 1),
        anti_spoofing_trend DOUBLE PRECISION,
        anti_spoofing_readiness TEXT NOT NULL CHECK (anti_spoofing_readiness IN ('ready', 'aspiring', 'lagging', 'no_data_available')),
        coordination_score DOUBLE PRECISION CHECK (coordination_score IS NULL OR coordination_score BETWEEN 0 AND 1),
        coordination_trend DOUBLE PRECISION,
        coordination_readiness TEXT NOT NULL CHECK (coordination_readiness IN ('ready', 'aspiring', 'lagging', 'no_data_available')),
        filtering_score DOUBLE PRECISION CHECK (filtering_score IS NULL OR filtering_score BETWEEN 0 AND 1),
        filtering_trend DOUBLE PRECISION,
        filtering_readiness TEXT NOT NULL CHECK (filtering_readiness IN ('ready', 'aspiring', 'lagging', 'no_data_available')),
        routing_information_irr_score DOUBLE PRECISION CHECK (routing_information_irr_score IS NULL OR routing_information_irr_score BETWEEN 0 AND 1),
        routing_information_irr_trend DOUBLE PRECISION,
        routing_information_irr_readiness TEXT NOT NULL CHECK (routing_information_irr_readiness IN ('ready', 'aspiring', 'lagging', 'no_data_available')),
        routing_information_rpki_score DOUBLE PRECISION CHECK (routing_information_rpki_score IS NULL OR routing_information_rpki_score BETWEEN 0 AND 1),
        routing_information_rpki_trend DOUBLE PRECISION,
        routing_information_rpki_readiness TEXT NOT NULL CHECK (routing_information_rpki_readiness IN ('ready', 'aspiring', 'lagging', 'no_data_available')),
        last_update_ts TIMESTAMPTZ NOT NULL,
        source TEXT NOT NULL REFERENCES data_source(source)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS manrs_country (
        country TEXT PRIMARY KEY REFERENCES country_location(country),
        anti_spoofing_score DOUBLE PRECISION CHECK (anti_spoofing_score IS NULL OR anti_spoofing_score BETWEEN 0 AND 1),
        anti_spoofing_trend DOUBLE PRECISION,
        anti_spoofing_ready_share DOUBLE PRECISION CHECK (anti_spoofing_ready_share IS NULL OR anti_spoofing_ready_share BETWEEN 0 AND 1),
        coordination_score DOUBLE PRECISION CHECK (coordination_score IS NULL OR coordination_score BETWEEN 0 AND 1),
        coordination_trend DOUBLE PRECISION,
        coordination_ready_share DOUBLE PRECISION CHECK (coordination_ready_share IS NULL OR coordination_ready_share BETWEEN 0 AND 1),
        filtering_score DOUBLE PRECISION CHECK (filtering_score IS NULL OR filtering_score BETWEEN 0 AND 1),
        filtering_trend DOUBLE PRECISION,
        filtering_ready_share DOUBLE PRECISION CHECK (filtering_ready_share IS NULL OR filtering_ready_share BETWEEN 0 AND 1),
        routing_information_irr_score DOUBLE PRECISION CHECK (routing_information_irr_score IS NULL OR routing_information_irr_score BETWEEN 0 AND 1),
        routing_information_irr_trend DOUBLE PRECISION,
        routing_information_irr_ready_share DOUBLE PRECISION CHECK (routing_information_irr_ready_share IS NULL OR routing_information_irr_ready_share BETWEEN 0 AND 1),
        routing_information_rpki_score DOUBLE PRECISION CHECK (routing_information_rpki_score IS NULL OR routing_information_rpki_score BETWEEN 0 AND 1),
        routing_information_rpki_trend DOUBLE PRECISION,
        routing_information_rpki_ready_share DOUBLE PRECISION CHECK (routing_information_rpki_ready_share IS NULL OR routing_information_rpki_ready_share BETWEEN 0 AND 1),
        last_update_ts TIMESTAMPTZ NOT NULL,
        source TEXT NOT NULL REFERENCES data_source(source)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS rpki_prefix (
        prefix CIDR NOT NULL,
        asn BIGINT NOT NULL CHECK (asn > 0 AND asn <= 4294967295),
        rpki_status TEXT NOT NULL CHECK (rpki_status IN ('valid', 'unknown', 'invalid_asn', 'invalid_length')),
        last_update_ts TIMESTAMPTZ NOT NULL,
        source TEXT NOT NULL REFERENCES data_source(source),
        PRIMARY KEY (prefix, asn)
    );
    """,
    """
    CREATE INDEX IF NOT EXISTS resolver_resolver_id_idx
        ON resolver (resolver_id);
    """,
    """
    CREATE INDEX IF NOT EXISTS resolver_service_protocol_port_idx
        ON resolver_service (protocol, port);
    """,
    """
    CREATE INDEX IF NOT EXISTS resolver_service_supported_protocol_port_idx
        ON resolver_service (supported, protocol, port);
    """,
    """
    CREATE INDEX IF NOT EXISTS resolver_dohpath_dohpath_idx
        ON resolver_dohpath (dohpath);
    """,
    """
    CREATE INDEX IF NOT EXISTS resolver_asn_asn_idx
        ON resolver_asn (asn);
    """,
    """
    CREATE INDEX IF NOT EXISTS resolver_prefix_prefix_gist_idx
        ON resolver_prefix USING gist (prefix inet_ops);
    """,
    """
    CREATE INDEX IF NOT EXISTS resolver_location_country_idx
        ON resolver_location (country);
    """,
    """
    CREATE INDEX IF NOT EXISTS resolver_domain_domain_idx
        ON resolver_domain (LOWER(domain));
    """,
    """
    CREATE INDEX IF NOT EXISTS resolver_verification_verifying_source_idx
        ON resolver_verification (verifying_source);
    """,
    """
    CREATE INDEX IF NOT EXISTS qmin_resolver_qmin_idx
        ON qmin_resolver (qmin);
    """,
    """
    CREATE INDEX IF NOT EXISTS qmin_resolver_max_minimise_count_idx
        ON qmin_resolver (max_minimise_count);
    """,
    """
    CREATE INDEX IF NOT EXISTS forwarder_forwarder_id_idx
        ON forwarder (forwarder_id);
    """,
    """
    CREATE INDEX IF NOT EXISTS forwarder_protocol_protocol_idx
        ON forwarder_protocol (protocol);
    """,
    """
    CREATE INDEX IF NOT EXISTS forwarder_protocol_supported_protocol_idx
        ON forwarder_protocol (supported, protocol);
    """,
    """
    CREATE INDEX IF NOT EXISTS forwarder_endpoint_endpoint_idx
        ON forwarder_endpoint (endpoint);
    """,
    """
    CREATE INDEX IF NOT EXISTS forwarder_asn_asn_idx
        ON forwarder_asn (asn);
    """,
    """
    CREATE INDEX IF NOT EXISTS forwarder_prefix_prefix_gist_idx
        ON forwarder_prefix USING gist (prefix inet_ops);
    """,
    """
    CREATE INDEX IF NOT EXISTS forwarder_location_country_idx
        ON forwarder_location (country);
    """,
    """
    CREATE INDEX IF NOT EXISTS forwarder_domain_domain_idx
        ON forwarder_domain (LOWER(domain));
    """,
    """
    CREATE INDEX IF NOT EXISTS forwarder_resolver_upstream_upstream_resolver_id_idx
        ON forwarder_resolver_upstream (upstream_resolver_id);
    """,
    """
    CREATE INDEX IF NOT EXISTS forwarder_forwarder_upstream_upstream_idx
        ON forwarder_forwarder_upstream (upstream_forwarder_id);
    """,
    """
    CREATE INDEX IF NOT EXISTS anycast_backing_prefix_gist_idx
        ON anycast USING gist (backing_prefix inet_ops);
    """,
    """
    CREATE INDEX IF NOT EXISTS anycast_prefix_gist_idx
        ON anycast USING gist (prefix inet_ops);
    """,
    """
    CREATE INDEX IF NOT EXISTS anycast_partial_idx
        ON anycast (partial);
    """,
    """
    CREATE INDEX IF NOT EXISTS anycast_asn_asn_idx
        ON anycast_asn (asn);
    """,
    """
    CREATE INDEX IF NOT EXISTS anycast_country_backend_country_idx
        ON anycast_country_backend (country);
    """,
    """
    CREATE INDEX IF NOT EXISTS anycast_asn_backend_asn_count_idx
        ON anycast_asn_backend (asn_count);
    """,
    """
    CREATE INDEX IF NOT EXISTS spoofing_asn_asn_idx
        ON spoofing_asn (asn);
    """,
    """
    CREATE INDEX IF NOT EXISTS spoofing_prefix_gist_idx
        ON spoofing USING gist (prefix inet_ops);
    """,
    """
    CREATE INDEX IF NOT EXISTS spoofing_country_country_idx
        ON spoofing_country (country);
    """,
    """
    CREATE INDEX IF NOT EXISTS dnssec_resolver_observation_ip_observed_at_idx
        ON dnssec_resolver_observation (ip, observed_at DESC);
    """,
    """
    CREATE INDEX IF NOT EXISTS dnssec_resolver_observation_observed_at_idx
        ON dnssec_resolver_observation (observed_at);
    """,
    """
    CREATE INDEX IF NOT EXISTS dnssec_resolver_observation_validates_idx
        ON dnssec_resolver_observation (validates);
    """,
    """
    CREATE INDEX IF NOT EXISTS rpki_prefix_prefix_gist_idx
        ON rpki_prefix USING gist (prefix inet_ops);
    """,
    """
    CREATE INDEX IF NOT EXISTS rpki_prefix_asn_idx
        ON rpki_prefix (asn);
    """,
    """
    CREATE INDEX IF NOT EXISTS rpki_prefix_status_idx
        ON rpki_prefix (rpki_status);
    """,
]


def apply_schema() -> None:
    dsn = build_dsn()
    logger.info("Applying schema to dns_resilience_observatory")
    with psycopg.connect(dsn, autocommit=True) as connection:
        with connection.cursor() as cursor:
            for index, statement in enumerate(STATEMENTS, start=1):
                logger.debug("Applying schema statement {index}/{total}", index=index, total=len(STATEMENTS))
                cursor.execute(statement)
    logger.info("Schema update complete")


def main() -> None:
    apply_schema()


if __name__ == "__main__":
    main()
