[tasks.py]
logging_tag = webpage_resolver_tasks

[update_webpage_resolvers.py]
logging_tag = update_webpage_resolvers.py
data_dir = ./data/webpage_resolver

[script_config.py]
logging_tag = webpage_resolver_script_config.py

[urls]
trickest_resolvers = https://raw.githubusercontent.com/trickest/resolvers/main/resolvers.txt

[url.trickest_resolvers]
headers = resolver_ip
no_header = true
mapping = ip:resolver_ip
modules = resolver
separator = ,
source = webpage-resolver.github.trickest
description = GitHub-hosted public resolver lists.
verified = false
force = false
